apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  CONFIG_URL: "http://config-server-svc"
  
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
data:
  HOSTNAME: "mysql-0.mysql"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: common-cm
data:
  SPRING_PROFILES_ACTIVE: prod
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-cm
data:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:7080/realms/master/protocol/openid-connect/certs"
